// Manus API type definitions

export interface ManusConfig {
  apiKey: string;
  baseUrl?: string;
  timeoutMs?: number;
  pollIntervalMs?: number;
}

// Task modes
export type ManusTaskMode = 'chat' | 'adaptive' | 'agent';

// Agent profiles
export type ManusAgentProfile =
  | 'manus-1.6'
  | 'manus-1.6-lite'
  | 'manus-1.6-max'
  | 'manus-1.5'
  | 'manus-1.5-lite'
  | 'speed';

// Task statuses
export type ManusTaskStatus = 'pending' | 'running' | 'completed' | 'failed';

// File upload request
export interface ManusFileUploadRequest {
  filename: string;
}

// File upload response
export interface ManusFileResponse {
  id: string;
  filename: string;
  status: string;
  upload_url?: string;
  upload_expires_at?: string;
  created_at: string;
}

// Task creation request
export type ManusFileIdAttachment = {
  filename: string;
  file_id: string;
};

export type ManusUrlAttachment = {
  filename: string;
  url: string;
  mimeType?: string;
};

export type ManusBase64Attachment = {
  filename: string;
  fileData: string;
};

export type ManusAttachment =
  | ManusFileIdAttachment
  | ManusUrlAttachment
  | ManusBase64Attachment;

export interface ManusTaskCreateRequest {
  prompt: string;
  attachments?: ManusAttachment[];
  taskMode?: ManusTaskMode;
  agentProfile?: ManusAgentProfile;
  connectors?: string[];
  createShareableLink?: boolean;
  taskId?: string;
}

// Task response from API
export interface ManusTaskResponse {
  id?: string;
  task_id?: string;
  title?: string;
  task_title?: string;
  status: ManusTaskStatus;
  url?: string;
  task_url?: string;
  share_url?: string;
  created_at: string;
  updated_at?: string;
  outputs?: ManusTaskOutput[];
  output?: ManusTaskOutputMessage[];
  error?: {
    code: string;
    message: string;
  };
}

// Task output (files generated by the task)
export interface ManusTaskOutput {
  type: string;
  url: string;
  filename?: string;
  mimeType?: string;
}

export interface ManusTaskOutputMessage {
  id?: string;
  status?: string;
  role?: string;
  type?: string;
  content?: ManusTaskOutputContent[];
}

export interface ManusTaskOutputContent {
  type: string;
  text?: string;
  fileUrl?: string;
  fileName?: string;
  mimeType?: string;
}

// Client interface
export interface ManusClient {
  uploadFile: (filename: string, fileUrl: string, mimeType?: string) => Promise<ManusFileResponse>;
  createTask: (request: ManusTaskCreateRequest) => Promise<ManusTaskResponse>;
  getTask: (taskId: string) => Promise<ManusTaskResponse>;
  waitForTask: (taskId: string) => Promise<ManusTaskResponse>;
  generatePresentation: (request: ManusGenerateRequest) => Promise<ManusGenerateResult>;
}

// High-level generation request (for backward compatibility)
export interface ManusGenerateRequest {
  prompt: string;
  files?: ManusFileInput[];
  outputFormat?: 'pptx';
  previousFeedback?: string;
  agentProfile?: ManusAgentProfile;
  taskMode?: ManusTaskMode;
  taskId?: string;
  previousOutputSignature?: string;
  inputUrls?: string[];
}

export interface ManusFileInput {
  name: string;
  url: string; // Public URL to the file
  mimeType?: string;
}

// Result returned by generatePresentation
export interface ManusGenerateResult {
  taskId: string;
  taskUrl: string;
  outputUrl: string;
  filename: string;
  pdfUrl?: string;
  pdfFilename?: string;
  outputSignature?: string; // Signature of all output files for detecting new output
}
