// Manus API type definitions

export interface ManusConfig {
  apiKey: string;
  baseUrl?: string;
  timeoutMs?: number;
  pollIntervalMs?: number;
}

// Task modes
export type ManusTaskMode = 'chat' | 'adaptive' | 'agent';

// Agent profiles
export type ManusAgentProfile =
  | 'manus-1.6'
  | 'manus-1.6-lite'
  | 'manus-1.6-max'
  | 'manus-1.5'
  | 'manus-1.5-lite'
  | 'speed';

// Task statuses
export type ManusTaskStatus = 'pending' | 'running' | 'completed' | 'failed';

// File upload request
export interface ManusFileUploadRequest {
  filename: string;
  fileUrl: string; // Publicly accessible URL
}

// File upload response
export interface ManusFileResponse {
  id: string;
  filename: string;
  status: string;
  upload_expires_at?: string;
  created_at: string;
}

// Task creation request
export interface ManusTaskCreateRequest {
  prompt: string;
  attachments?: string[]; // File IDs or URLs
  taskMode?: ManusTaskMode;
  agentProfile?: ManusAgentProfile;
  connectors?: string[];
  createShareableLink?: boolean;
}

// Task response from API
export interface ManusTaskResponse {
  id: string;
  title?: string;
  status: ManusTaskStatus;
  url?: string;
  created_at: string;
  updated_at?: string;
  outputs?: ManusTaskOutput[];
  error?: {
    code: string;
    message: string;
  };
}

// Task output (files generated by the task)
export interface ManusTaskOutput {
  type: string;
  url: string;
  filename?: string;
  mimeType?: string;
}

// Client interface
export interface ManusClient {
  uploadFile: (filename: string, fileUrl: string) => Promise<ManusFileResponse>;
  createTask: (request: ManusTaskCreateRequest) => Promise<ManusTaskResponse>;
  getTask: (taskId: string) => Promise<ManusTaskResponse>;
  waitForTask: (taskId: string) => Promise<ManusTaskResponse>;
  generatePresentation: (request: ManusGenerateRequest) => Promise<ManusGenerateResult>;
}

// High-level generation request (for backward compatibility)
export interface ManusGenerateRequest {
  prompt: string;
  files?: ManusFileInput[];
  outputFormat?: 'pptx';
  previousFeedback?: string;
  agentProfile?: ManusAgentProfile;
  taskMode?: ManusTaskMode;
}

export interface ManusFileInput {
  name: string;
  url: string; // Public URL to the file
  mimeType?: string;
}

// Result returned by generatePresentation
export interface ManusGenerateResult {
  taskId: string;
  taskUrl: string;
  outputUrl: string;
  filename: string;
}
